const apartment = [
    {
        'id' : 0,
        'name' : 'Washington Avenue',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/WgRdY6h/washington.jpg',
        'price': '$194',
        'rent':'',
        'charge':'5,000/= Tk per month',        
    },
    {
        'id' : 1,
        'name' : 'Family Apartment Three',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/n7r1Wk0/family.jpg',
        'price': '$356',
        'rent':'',
        'charge':'8,000/= Tk per month',       
    },
    {
        'id' : 2,
        'name' : 'Gorgeous house ',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/txFfpzP/gorgeous.jpg',
        'price': '256',
        'rent':'',
        'charge':'6,000/= Tk per month',        
    },
    {
        'id' : 3,
        'name' : 'Luxury villa ',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/CVqD88v/luxury.jpg',
        'price': '$345',
        'rent':'',
        'charge':'8,000/= Tk per month',        
    },
    {
        'id' : 4,
        'name' : 'Epic Huda Palacio',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/5Wh3Q4H/palacio.jpg',
        'price': '$536',
        'rent':'',
        'charge':'5,000/= Tk per month',        
    },
    {
        'id' : 5,
        'name' : 'Washington Avenue',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/HtxnRBw/avenue.jpg',
        'price': '$283',
        'rent':'',
        'charge':'8,000/= Tk per month',        
    },
    // {
    //     'id' : '',
    //     'name' : '',
    //     'address': '',
    //     'bed':'',
    //     'bath':'',
    //     'img' : '',
    //     'price': '',
    //     'homeDetails': '',
    //     'rent':'',
    //     'charge':'',
    //     'sequrity':'',
    //     'policy':'',
    //     'propertyDetails':''
    // },
      
]
export default apartment;
